const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DEFAULT_CATS=['红茶','绿茶','乌龙茶','白茶','黄茶','黑茶','花茶','茶叶通用'];
const TERMS={aroma:['花香','蜜香','果香','甜香','毫香','嫩香','清香','桂圆香','薯香','焦糖香','木香','烟香'],taste:['甜醇','醇厚','鲜爽','浓醇','回甘','生津','顺滑','苦','涩','刺激','清甜','醇和']};
let db,currentBatch=null,currentSample=null,photoData='';
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('TeaSampleLogDB',1);r.onupgradeneeded=e=>{const d=e.target.result;d.createObjectStore('batches',{keyPath:'id'});d.createObjectStore('samples',{keyPath:'id'});d.createObjectStore('settings',{keyPath:'key'})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function put(store,obj){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>res(obj);r.onerror=()=>rej(r.error)})}
function getAll(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function del(store,id){return new Promise((res,rej)=>{const r=tx(store,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function dateText(ts){return new Date(ts).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
async function getCats(){const all=await getAll('settings');const s=all.find(x=>x.key==='categories');return s?.value||DEFAULT_CATS}
async function renderCats(){const cats=await getCats();$('#teaCategory').innerHTML=cats.map(c=>`<option>${esc(c)}</option>`).join('');$('#categoryList').innerHTML=cats.map(c=>`<span class="tag">${esc(c)} ${DEFAULT_CATS.includes(c)?'':`<button data-delcat="${esc(c)}">×</button>`}</span>`).join('');$$('[data-delcat]').forEach(b=>b.onclick=async()=>{const n=b.dataset.delcat;await put('settings',{key:'categories',value:cats.filter(x=>x!==n)});renderCats()})}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));if(id==='home')renderHome();if(id==='history')renderHistory();if(id==='settings')renderCats();scrollTo(0,0)}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
async function renderHome(){const bs=(await getAll('batches')).sort((a,b)=>b.createdAt-a.createdAt), ss=await getAll('samples');$('#batchCount').textContent=bs.length;$('#sampleCount').textContent=ss.length;const t=new Date().toDateString();$('#todayCount').textContent=ss.filter(s=>new Date(s.createdAt).toDateString()===t).length;const box=$('#recentBatches');if(!bs.length){box.className='cards empty';box.textContent='暂无记录';return}box.className='cards';box.innerHTML=bs.slice(0,8).map(b=>{const n=ss.filter(s=>s.batchId===b.id).length;return `<article class="card" data-batch="${b.id}"><div class="grow"><h3>${esc(b.name)}</h3><p>${esc(b.category)} · ${dateText(b.createdAt)} · ${n}个样品</p></div><b>›</b></article>`}).join('');$$('[data-batch]').forEach(x=>x.onclick=()=>openBatch(x.dataset.batch))}
$('#batchForm').onsubmit=async e=>{e.preventDefault();const b={id:uid(),name:$('#batchName').value.trim(),category:$('#teaCategory').value,place:$('#batchPlace').value.trim(),note:$('#batchNote').value.trim(),createdAt:Date.now()};await put('batches',b);e.target.reset();openBatch(b.id)};
async function openBatch(id){const bs=await getAll('batches');currentBatch=bs.find(b=>b.id===id);if(!currentBatch)return;$('#detailTitle').textContent=currentBatch.name;$('#detailMeta').textContent=`${currentBatch.category} · ${dateText(currentBatch.createdAt)}${currentBatch.place?' · '+currentBatch.place:''}`;await renderSamples();go('batchDetail')}
async function renderSamples(){const all=(await getAll('samples')).filter(s=>s.batchId===currentBatch.id).sort((a,b)=>a.order-b.order);const box=$('#sampleList');if(!all.length){box.className='cards empty';box.textContent='暂无样品';return}box.className='cards';box.innerHTML=all.map(s=>`<article class="card" data-sample="${s.id}">${s.photo?`<img src="${s.photo}">`:'<div style="width:68px;height:68px;border-radius:12px;background:#eee"></div>'}<div class="grow"><h3>${String(s.order).padStart(2,'0')}号 ${esc(s.name||'未命名样品')}</h3><p>${esc(s.code||'无编号')}${s.company?' · '+esc(s.company):''}</p><p>${esc([s.myAroma,s.myTaste].filter(Boolean).join('；')||'尚未填写品评')}</p></div><b>›</b></article>`).join('');$$('[data-sample]').forEach(x=>x.onclick=()=>editSample(x.dataset.sample))}
$('#addSampleBtn').onclick=()=>editSample();$('#sampleBack').onclick=()=>openBatch(currentBatch.id);
async function editSample(id){const all=await getAll('samples');currentSample=id?all.find(s=>s.id===id):null;const order=currentSample?.order||all.filter(s=>s.batchId===currentBatch.id).length+1;$('#sampleTitle').textContent=`${String(order).padStart(2,'0')}号样品`;for(const [k,id2] of Object.entries({name:'sampleName',code:'sampleCode',company:'sampleCompany',myAroma:'myAroma',myTaste:'myTaste',otherAroma:'otherAroma',otherTaste:'otherTaste',note:'sampleNote'}))$('#'+id2).value=currentSample?.[k]||'';photoData=currentSample?.photo||'';showPhoto();$('#deleteSampleBtn').style.display=currentSample?'block':'none';go('sampleEdit')}
function showPhoto(){const im=$('#samplePreview'),hint=$('#photoHint');if(photoData){im.src=photoData;im.style.display='block';hint.style.display='none'}else{im.removeAttribute('src');im.style.display='none';hint.style.display='block'}}
$('#samplePhoto').onchange=async e=>{const f=e.target.files[0];if(!f)return;photoData=await compressImage(f);showPhoto()};
function compressImage(file){return new Promise((res,rej)=>{const img=new Image,fr=new FileReader;fr.onload=()=>img.src=fr.result;fr.onerror=rej;img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=img.width*scale;c.height=img.height*scale;c.getContext('2d').drawImage(img,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.72))};fr.readAsDataURL(file)})}
$('#sampleForm').onsubmit=async e=>{e.preventDefault();const existing=await getAll('samples'),order=currentSample?.order||existing.filter(s=>s.batchId===currentBatch.id).length+1;const s={id:currentSample?.id||uid(),batchId:currentBatch.id,order,photo:photoData,name:$('#sampleName').value.trim(),code:$('#sampleCode').value.trim(),company:$('#sampleCompany').value.trim(),myAroma:$('#myAroma').value.trim(),myTaste:$('#myTaste').value.trim(),otherAroma:$('#otherAroma').value.trim(),otherTaste:$('#otherTaste').value.trim(),note:$('#sampleNote').value.trim(),createdAt:currentSample?.createdAt||Date.now(),updatedAt:Date.now()};await put('samples',s);openBatch(currentBatch.id)};
$('#deleteSampleBtn').onclick=async()=>{if(currentSample&&confirm('确定删除这个样品吗？')){await del('samples',currentSample.id);openBatch(currentBatch.id)}};
function makeChips(){for(const box of $$('.chips')){const type=box.dataset.target.toLowerCase().includes('aroma')?'aroma':'taste';box.innerHTML=TERMS[type].map(t=>`<button type="button" class="chip">${t}</button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const ta=$('#'+box.dataset.target),parts=ta.value.split(/[，,、；;\s]+/).filter(Boolean);if(!parts.includes(b.textContent))parts.push(b.textContent);ta.value=parts.join('、')})}}makeChips();
async function renderHistory(){const q=$('#searchInput').value.trim().toLowerCase(), bs=await getAll('batches'), ss=(await getAll('samples')).sort((a,b)=>b.createdAt-a.createdAt).filter(s=>!q||[s.name,s.code,s.company,s.myAroma,s.myTaste,s.otherAroma,s.otherTaste,s.note].join(' ').toLowerCase().includes(q));const box=$('#historyList');if(!ss.length){box.className='cards empty';box.textContent='没有匹配记录';return}box.className='cards';box.innerHTML=ss.map(s=>{const b=bs.find(x=>x.id===s.batchId);return `<article class="card" data-hsample="${s.id}" data-hbatch="${s.batchId}">${s.photo?`<img src="${s.photo}">`:'<div style="width:68px;height:68px;border-radius:12px;background:#eee"></div>'}<div class="grow"><h3>${esc(s.name||String(s.order).padStart(2,'0')+'号样品')}</h3><p>${esc(b?.name||'未知批次')} · ${esc(s.company||s.code||'')}</p></div><b>›</b></article>`}).join('');$$('[data-hsample]').forEach(x=>x.onclick=async()=>{await openBatch(x.dataset.hbatch);editSample(x.dataset.hsample)})}
$('#searchInput').oninput=renderHistory;
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
async function exportCSV(batchId){const bs=await getAll('batches'), all=await getAll('samples'), ss=batchId?all.filter(s=>s.batchId===batchId):all;const head=['批次','日期','茶类','顺序号','样品名称','样品编号','公司','我的香气','我的滋味','他人香气','他人滋味','备注'];const rows=ss.sort((a,b)=>a.createdAt-b.createdAt).map(s=>{const b=bs.find(x=>x.id===s.batchId)||{};return [b.name,dateText(s.createdAt),b.category,s.order,s.name,s.code,s.company,s.myAroma,s.myTaste,s.otherAroma,s.otherTaste,s.note]});download('\ufeff'+[head,...rows].map(r=>r.map(csvCell).join(',')).join('\n'),batchId?`${currentBatch.name}.csv`:'茶样志-全部记录.csv','text/csv;charset=utf-8')}
function download(data,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#exportBatchBtn').onclick=()=>exportCSV(currentBatch.id);$('#exportAllBtn').onclick=()=>exportCSV();
$('#backupBtn').onclick=async()=>download(JSON.stringify({version:1,batches:await getAll('batches'),samples:await getAll('samples'),settings:await getAll('settings')},null,2),`茶样志备份-${new Date().toISOString().slice(0,10)}.json`,'application/json');
$('#restoreInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());for(const x of data.batches||[])await put('batches',x);for(const x of data.samples||[])await put('samples',x);for(const x of data.settings||[])await put('settings',x);alert('恢复完成');renderHome()}catch{alert('备份文件无法读取')}};
$('#clearBtn').onclick=async()=>{if(!confirm('此操作会删除全部批次、样品和照片，确定继续吗？'))return;for(const s of ['batches','samples','settings'])await new Promise((res,rej)=>{const r=tx(s,'readwrite').clear();r.onsuccess=res;r.onerror=rej});await renderCats();renderHome();alert('已清空')};
$('#addCategoryBtn').onclick=async()=>{const n=$('#newCategory').value.trim();if(!n)return;const c=await getCats();if(!c.includes(n))c.push(n);await put('settings',{key:'categories',value:c});$('#newCategory').value='';renderCats()};
$('#ocrBtn').onclick=async()=>{if(!photoData)return alert('请先拍摄或选择样品袋照片');$('#ocrStatus').textContent='正在加载识别组件…';try{if(!window.Tesseract){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}$('#ocrStatus').textContent='正在识别，请保持页面打开…';const r=await Tesseract.recognize(photoData,'chi_sim+eng');const text=r.data.text.trim();$('#sampleNote').value=($('#sampleNote').value?$('#sampleNote').value+'\n':'')+'【包装识别文字】\n'+text;const lines=text.split(/\n/).map(x=>x.trim()).filter(x=>x.length>1);if(!$('#sampleCode').value){const code=lines.find(x=>/[A-Z0-9-]{4,}/i.test(x));if(code)$('#sampleCode').value=code.slice(0,40)}if(!$('#sampleCompany').value){const co=lines.find(x=>/(公司|茶业|集团|合作社)/.test(x));if(co)$('#sampleCompany').value=co.slice(0,40)}if(!$('#sampleName').value){const nm=lines.find(x=>/(红茶|绿茶|乌龙|小种|金骏眉|工夫|茶)/.test(x)&&!/(公司|茶业)/.test(x));if(nm)$('#sampleName').value=nm.slice(0,30)}$('#ocrStatus').textContent='识别完成，请检查并修改结果'}catch(e){$('#ocrStatus').textContent='识别失败，请检查网络或手动填写';alert('OCR 组件未能加载。你仍可手动填写名称、编号和公司。')}};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null}else alert('在 iPhone Safari 中，请点击“分享”→“添加到主屏幕”')};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
(async()=>{await openDB();await renderCats();await renderHome()})();
